### ISSUE TITLE
Again old problems, on new version...

### ISSUE THREAD

**Issue by h4ppyboy** [Schottky-spi/UpgradingCorePlus#13]
https://youtu.be/JSGRXq2CQKU

**Comment by Schottky-spi** [comment]
You are seeing this issue because armor caps out at 30.0 Armor-points in Minecraft. Unfortunately, there is nothing I can do about this. You can combine protection and an upgrading core to get better protection results, if you want.

**Comment by h4ppyboy** [comment]
> You are seeing this issue because armor caps out at 30.0 Armor-points in Minecraft. Unfortunately, there is nothing I can do about this. You can combine protection and an upgrading core to get better protection results, if you want.

But can u fix issue with netherite axe?

**Comment by Schottky-spi** [comment]
Yea, I already fixed it but didn't publish it. Coming right up!
